-- DONNEES
 
INSERT INTO DONNEES (CARACTERISTIQUE, ID_P, VALEUR)
VALUES
('Tailles', 1, '41');


INSERT INTO DONNEES (CARACTERISTIQUE, ID_P, VALEUR)
VALUES
('Tailles', 2, '35');


INSERT INTO DONNEES (CARACTERISTIQUE, ID_P, VALEUR)
VALUES
('Tailles', 3, 'L');

 
INSERT INTO DONNEES (CARACTERISTIQUE, ID_P, VALEUR)
VALUES
('Tailles', 4, 'XS');


INSERT INTO DONNEES (CARACTERISTIQUE, ID_P, VALEUR)
VALUES
('Tailles', 5, '46');


INSERT INTO DONNEES (CARACTERISTIQUE, ID_P, VALEUR)
VALUES
('Tailles', 6, '39');


INSERT INTO DONNEES (CARACTERISTIQUE, ID_P, VALEUR)
VALUES
('Tailles', 7, '43');

INSERT INTO DONNEES (CARACTERISTIQUE, ID_P, VALEUR)
VALUES
('Année', 9, '1992');

INSERT INTO DONNEES (CARACTERISTIQUE, ID_P, VALEUR)
VALUES
('Longueur:', 11, '32,5cm');

INSERT INTO DONNEES (CARACTERISTIQUE, ID_P, VALEUR)
VALUES
('Largeur:', 11, '24cm');

INSERT INTO DONNEES (CARACTERISTIQUE, ID_P, VALEUR)
VALUES
('Matière:', 12, 'Laiton');


INSERT INTO DONNEES (CARACTERISTIQUE, ID_P, VALEUR)
VALUES
('Diamètre:', 13, '20cm');

INSERT INTO DONNEES (CARACTERISTIQUE, ID_P, VALEUR)
VALUES
('Année:', 13, '462-466');